
package com.ccg.webservice.czservice.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* SendServiceService service = new SendServiceService();
* SendService portType = service.getSendServicePort();
* portType.sendOrg(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "SendServiceService", targetNamespace = "http://czprovide.webservice.oapro.zjcw.com/", wsdlLocation = "http://localhost:8080/czxt/webservice/sendServie?wsdl")
public class SendServiceService extends Service {

	private final static URL SENDSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.ccg.webservice.czservice.wsdl.SendServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ccg.webservice.czservice.wsdl.SendServiceService.class.getResource(".");
			url = new URL(baseUrl, "http://localhost:8080/czxt/webservice/sendServie?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://localhost:8080/czxt/webservice/sendServie?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SENDSERVICESERVICE_WSDL_LOCATION = url;
	}

	public SendServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SendServiceService() {
		super(SENDSERVICESERVICE_WSDL_LOCATION,
				new QName("http://czprovide.webservice.oapro.zjcw.com/", "SendServiceService"));
	}

	/**
	 * 
	 * @return returns SendService
	 */
	@WebEndpoint(name = "SendServicePort")
	public SendService getSendServicePort() {
		return super.getPort(new QName("http://czprovide.webservice.oapro.zjcw.com/", "SendServicePort"),
				SendService.class);
	}

}
