
package com.ccg.webservice.czservice.consumer3.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* SendCzServiceService service = new SendCzServiceService();
* SendCzService portType = service.getSendCzServicePort();
* portType.ifService(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "SendCzServiceService", targetNamespace = "http://provider.czservice.webservice.oapro.zjcw.com/", wsdlLocation = "http://localhost:8080/czxt/webservice/sendCzService?wsdl")
public class SendCzServiceService extends Service {

	private final static URL SENDCZSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.ccg.webservice.czservice.consumer3.wsdl.SendCzServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ccg.webservice.czservice.consumer3.wsdl.SendCzServiceService.class.getResource(".");
			url = new URL(baseUrl, "http://localhost:8080/czxt/webservice/sendCzService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://localhost:8080/czxt/webservice/sendCzService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SENDCZSERVICESERVICE_WSDL_LOCATION = url;
	}

	public SendCzServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SendCzServiceService() {
		super(SENDCZSERVICESERVICE_WSDL_LOCATION,
				new QName("http://provider.czservice.webservice.oapro.zjcw.com/", "SendCzServiceService"));
	}

	/**
	 * 
	 * @return returns SendCzService
	 */
	@WebEndpoint(name = "SendCzServicePort")
	public SendCzService getSendCzServicePort() {
		return super.getPort(new QName("http://provider.czservice.webservice.oapro.zjcw.com/", "SendCzServicePort"),
				SendCzService.class);
	}

}
